#ifndef _EDGE_DEFINES_H_
#define  _EDGE_DEFINES_H_

#define OCALL_PRINT_BUFFER 1
#define OCALL_SEND_REPORT 2
#define OCALL_WAIT_FOR_MESSAGE 3
#define OCALL_SEND_REPLY 4
#define OCALL_CREATE_CHANNEL 5
#define OCALL_RECEIVE_REMOTE_REPORT 6
#define OCALL_RECEIVE_REMOTE_REPORT_ACK 7
#define OCALL_CREATE_CHANNEL_ACK 8
#define OCALL_SEND_ON_CHANNEL 9
#define OCALL_PROFILE 10

#endif /* _EDGE_DEFINES_H_ */
